#!/bin/sh
# moonfollow fixture corpus: synthetic walking videos with mathematically
# known landing times, generated by ffmpeg geq, each asserted end to end.
# Every case states its expectation inline; the script exits nonzero on the
# first failure.
#
# usage: examples/fixtures.sh [output-dir]   (default /tmp/moonfollow-fixtures)
set -e
cd "$(dirname "$0")/.."
OUT=${1:-/tmp/moonfollow-fixtures}
mkdir -p "$OUT"
PASS=0

ok() { echo "  PASS  $1"; PASS=$((PASS+1)); }
fail() { echo "  FAIL  $1: $2"; exit 1; }

# steps count of a track/edge json
steps_count() {
  moon run cmd/moonfollow -- steps "$1" | head -1 | grep -oE '[0-9]+ steps' | grep -oE '[0-9]+'
}
# Nth timecode line
tc_line() {
  moon run cmd/moonfollow -- steps "$1" | grep -E '^[0-9]{2}:' | sed -n "$2p" | cut -d' ' -f1
}

# walker geq at 160x90: body x[70,90) y[30,60), legs x[72,78)/[82,88),
# ground row 88, lift 30 px, stride S s, left lands at 0.30+k*S,
# right at RPH+k*S
walker_lum() { # stride right_phase
  # sin argument normalised by the stride: exactly one ground touch per
  # cycle at any stride (a bare sin(PI*mod(...)) touches down at every
  # integer u inside the cycle when stride > 1)
  echo "if(between(X,70,89)*between(Y,30,59),200, if(between(X,72,77)*gte(Y,60)*lt(Y,88-30*abs(sin(PI*mod(T-0.30,$1)/$1))),200, if(between(X,82,87)*gte(Y,60)*lt(Y,88-30*abs(sin(PI*mod(T-$2,$1)/$1))),200,20)))"
}

make_walker() { # file fps dur stride right_phase
  ffmpeg -v error -y -f lavfi -i "color=c=0x141414:s=160x90:r=$2:d=$3" \
    -vf "geq=lum='$(walker_lum "$4" "$5")':cb=128:cr=128" \
    -pix_fmt yuv420p -c:v libx264 "$OUT/$1" 2>/dev/null
}

# ---------------------------------------------------------------- fps matrix
# stride 1.0 s, left lands 0.30+k (warmup eats the first below frame 8),
# right 0.82+k
for spec in "fps24:24:9" "fps25:25:9" "fps30:30:10" "fps50:50:10"; do
  name=$(echo "$spec" | cut -d: -f1); rate=$(echo "$spec" | cut -d: -f2); want=$(echo "$spec" | cut -d: -f3)
  make_walker "$name.mp4" "$rate" 5 1.0 0.82
  moon run cmd/moonfollow -- detect "$OUT/$name.mp4" -o "$OUT/$name.json" > /dev/null
  got=$(steps_count "$OUT/$name.json")
  [ "$got" = "$want" ] && ok "$name ($rate fps): $got steps" || fail "$name" "got $got steps, want $want"
done

# 29.97 drop-frame: same timeline, SMPTE uses ';' and skip numbers at minute
# starts -- first landing after warmup is the right foot at 0.82 s
make_walker fps2997.mp4 30000/1001 5 1.0 0.82
moon run cmd/moonfollow -- detect "$OUT/fps2997.mp4" -o "$OUT/fps2997.json" > /dev/null
got=$(steps_count "$OUT/fps2997.json")
[ "$got" = "10" ] && ok "fps2997 (DF): $got steps" || fail "fps2997" "got $got, want 10"
tc=$(tc_line "$OUT/fps2997.json" 1)
echo "$tc" | grep -q ';' && ok "fps2997 (DF): drop-frame separator in '$tc'" \
  || fail "fps2997" "timecode '$tc' lacks ';'"

# ------------------------------------------------------------------- cadence
# slow: stride 1.6 s (L 1.9,3.5,5.1; R 0.82,2.42,4.02,5.62 in 6.5 s)
make_walker slow.mp4 25 6.5 1.6 1.12
moon run cmd/moonfollow -- detect "$OUT/slow.mp4" -o "$OUT/slow.json" > /dev/null
got=$(steps_count "$OUT/slow.json")
[ "$got" = "7" ] && ok "slow walk (1.6 s stride): $got steps" || fail "slow" "got $got, want 7"
tc=$(tc_line "$OUT/slow.json" 1)
[ "$tc" = "00:00:01:03" ] && ok "slow walk: first landing 00:00:01:03 (right foot, 1.12 s)" \
  || fail "slow" "first timecode '$tc'"

# fast: stride 0.5 s (L 0.8..4.8 = 9; R 0.82..4.82 = 9)
make_walker fast.mp4 25 5 0.5 0.57
moon run cmd/moonfollow -- detect "$OUT/fast.mp4" -o "$OUT/fast.json" > /dev/null
got=$(steps_count "$OUT/fast.json")
[ "$got" = "18" ] && ok "fast walk (0.5 s stride): $got steps" || fail "fast" "got $got, want 18"

# ------------------------------------------------------------- profile, RTL
# a stepping sideways walker: the leading edge is a staircase -- it ramps
# forward during the last 0.25 s of each 0.9 s stride and dwells while the
# foot is planted. Landings at 0.80 + 0.9 k.
ffmpeg -v error -y -f lavfi -i "color=c=0x141414:s=200x90:r=25:d=6" \
  -vf "geq=lum='st(9,14*(max(floor((T-0.8)/0.9),-1)+1)+if(gt(T,0.9*(floor((T-0.8)/0.9)+1)+0.55),(T-(0.9*(floor((T-0.8)/0.9)+1)+0.55))*56,0));st(8,if(gt(T,0.9*(floor((T-0.8)/0.9)+1)+0.55),20*sin(PI*(T-(0.9*(floor((T-0.8)/0.9)+1)+0.55))*4),0));if(between(X,ld(9)-21,ld(9)-3)*between(Y,30,60),200, if(between(X,ld(9)-13,ld(9)-8)*gte(Y,60)*lte(Y,88),200, if(between(X,ld(9)-5,ld(9)-1)*gte(Y,60)*lt(Y,88-ld(8)),200,20)))':cb=128:cr=128" \
  -pix_fmt yuv420p -c:v libx264 "$OUT/profile-ltr.mp4" 2>/dev/null
ffmpeg -v error -y -i "$OUT/profile-ltr.mp4" -vf hflip -c:v libx264 "$OUT/profile-rtl.mp4" 2>/dev/null
# LTR is exact; RTL can lose the first landing: until the direction lock
# the detector follows the trailing edge, and the lock window straddles the
# first dwell
moon run cmd/moonfollow -- detect "$OUT/profile-ltr.mp4" --profile -o "$OUT/profile-ltr.json" > /dev/null
got=$(steps_count "$OUT/profile-ltr.json")
[ "$got" = "6" ] && ok "profile ltr: $got landings from the staircase edge" \
  || fail "profile-ltr" "got $got, want 6"
tc=$(tc_line "$OUT/profile-ltr.json" 1)
[ "$tc" = "00:00:00:20" ] && ok "profile ltr: first landing 00:00:00:20 (0.80 s)" \
  || fail "profile-ltr" "first timecode '$tc'"
moon run cmd/moonfollow -- detect "$OUT/profile-rtl.mp4" --profile -o "$OUT/profile-rtl.json" > /dev/null
got=$(steps_count "$OUT/profile-rtl.json")
[ "$got" -ge 5 ] && ok "profile rtl: $got landings (first may fall inside the direction-lock window)" \
  || fail "profile-rtl" "got $got, want >= 5"

# ---------------------------------------------------------------- multi-person
# three walkers hstacked: strides 1.0 / 0.8 / 1.0 with distinct phases
P1=$(walker_lum 1.0 0.82)
P2="if(between(X,70,89)*between(Y,30,59),200, if(between(X,72,77)*gte(Y,60)*lt(Y,88-30*abs(sin(PI*mod(T-0.52,0.8)))),200, if(between(X,82,87)*gte(Y,60)*lt(Y,88-30*abs(sin(PI*mod(T-0.92,0.8)))),200,20)))"
P3="if(between(X,70,89)*between(Y,30,59),200, if(between(X,72,77)*gte(Y,60)*lt(Y,88-30*abs(sin(PI*mod(T-0.10,1)))),200, if(between(X,82,87)*gte(Y,60)*lt(Y,88-30*abs(sin(PI*mod(T-0.60,1)))),200,20)))"
ffmpeg -v error -y \
  -f lavfi -i "color=c=0x141414:s=160x90:r=25:d=5" \
  -f lavfi -i "color=c=0x141414:s=160x90:r=25:d=5" \
  -f lavfi -i "color=c=0x141414:s=160x90:r=25:d=5" \
  -filter_complex "[0:v]geq=lum='$P1':cb=128:cr=128[a];[1:v]geq=lum='$P2':cb=128:cr=128[b];[2:v]geq=lum='$P3':cb=128:cr=128[c];[a][b][c]hstack=3" \
  -pix_fmt yuv420p -c:v libx264 "$OUT/walker-three.mp4" 2>/dev/null
moon run cmd/moonfollow -- detect "$OUT/walker-three.mp4" --multi -o "$OUT/three.json" > /dev/null
n=$(grep -o '"video"' "$OUT/three.json" | wc -l | tr -d ' ')
[ "$n" = "3" ] && ok "three walkers: 3 person tracks" || fail "three" "got $n person tracks"
got=$(steps_count "$OUT/three.json")
[ "$got" -ge 25 ] && ok "three walkers: $got steps across persons" || fail "three" "only $got steps"

# --------------------------------------------- noisy multi-person align
# three walkers' footsteps delayed 0.4 s and buried in pink noise (fixed
# seed): align must use every person's landings -- matching only the
# dominant track against the mixed audio aliases to the inter-person phase
# shift -- and the dense-grid tolerance must not saturate the score
ffmpeg -v error -y -f lavfi -i "sine=frequency=160:duration=0.06,volume=0.6,afade=t=out:st=0.01:d=0.05" -acodec pcm_s16le -ac 1 "$OUT/step.wav"
moon run cmd/moonfollow -- run "$OUT/three.json" --sfx "$OUT/step.wav" -o "$OUT/three-steps.wav" > /dev/null
ffmpeg -v error -y -i "$OUT/three-steps.wav" -af "adelay=400" -acodec pcm_s16le "$OUT/three-late.wav"
ffmpeg -v error -y -i "$OUT/three-late.wav" -f lavfi -i "anoisesrc=color=pink:amplitude=0.2:seed=42" -filter_complex "[0:a][1:a]amix=inputs=2:duration=first:normalize=0" -acodec pcm_s16le "$OUT/three-noisy.wav"
moon run cmd/moonfollow -- mux "$OUT/walker-three.mp4" "$OUT/three-noisy.wav" -o "$OUT/three-noisy.mp4" > /dev/null
out=$(moon run cmd/moonfollow -- align "$OUT/three-noisy.mp4" -o "$OUT/three-fixed.mp4" 2>&1)
echo "$out" | grep -q "late by 39[0-9]\." && ok "noisy three-walker align: 0.4 s delay recovered from pink noise" \
  || fail "noise-align" "offset line: $(echo "$out" | head -1)"

# ------------------------------------------------------------------ polarity
# dark walker on a bright street (photometric inverse of the base)
ffmpeg -v error -y -f lavfi -i "color=c=0xc8c8c8:s=160x90:r=25:d=5" \
  -vf "geq=lum='if(between(X,70,89)*between(Y,30,59),20, if(between(X,72,77)*gte(Y,60)*lt(Y,88-30*abs(sin(PI*mod(T-0.30,1)))),20, if(between(X,82,87)*gte(Y,60)*lt(Y,88-30*abs(sin(PI*mod(T-0.82,1)))),20,200)))':cb=128:cr=128" \
  -pix_fmt yuv420p -c:v libx264 "$OUT/dark-walker.mp4" 2>/dev/null
moon run cmd/moonfollow -- detect "$OUT/dark-walker.mp4" -o "$OUT/dark-walker.json" > /dev/null
got=$(steps_count "$OUT/dark-walker.json")
[ "$got" = "9" ] && ok "dark walker (auto polarity): $got steps" || fail "dark" "got $got, want 9"

# --------------------------------------------------------------------- scale
# double-size walker at 320x180 (body x[140,180) y[60,120), ground 176, lift 60)
ffmpeg -v error -y -f lavfi -i "color=c=0x141414:s=320x180:r=25:d=5" \
  -vf "geq=lum='if(between(X,140,179)*between(Y,60,119),200, if(between(X,144,155)*gte(Y,120)*lt(Y,176-60*abs(sin(PI*mod(T-0.30,1)))),200, if(between(X,164,175)*gte(Y,120)*lt(Y,176-60*abs(sin(PI*mod(T-0.82,1)))),200,20)))':cb=128:cr=128" \
  -pix_fmt yuv420p -c:v libx264 "$OUT/big-walker.mp4" 2>/dev/null
moon run cmd/moonfollow -- detect "$OUT/big-walker.mp4" -o "$OUT/big-walker.json" > /dev/null
got=$(steps_count "$OUT/big-walker.json")
[ "$got" = "9" ] && ok "2x walker (320x180): $got steps" || fail "big" "got $got, want 9"

# ----------------------------------------------------------------- late entry
# empty scene for the first 2 s, walker steps in at T=2 (L 2.3,3.3,4.3; R 2.82,3.82,4.82)
ffmpeg -v error -y -f lavfi -i "color=c=0x141414:s=160x90:r=25:d=5" \
  -vf "geq=lum='if(between(X,70,89)*between(Y,30,59)*gt(T,2),200, if(between(X,72,77)*gte(Y,60)*lt(Y,88-30*abs(sin(PI*mod(T-0.30,1))))*gt(T,2),200, if(between(X,82,87)*gte(Y,60)*lt(Y,88-30*abs(sin(PI*mod(T-0.82,1))))*gt(T,2),200,20)))':cb=128:cr=128" \
  -pix_fmt yuv420p -c:v libx264 "$OUT/late-entry.mp4" 2>/dev/null
moon run cmd/moonfollow -- detect "$OUT/late-entry.mp4" -o "$OUT/late-entry.json" > /dev/null
got=$(steps_count "$OUT/late-entry.json")
[ "$got" = "6" ] && ok "late entry (walker from T=2): $got steps" || fail "late" "got $got, want 6"
tc=$(tc_line "$OUT/late-entry.json" 1)
[ "$tc" = "00:00:02:07" ] && ok "late entry: first landing 00:00:02:07 (left foot, 2.30 s)" \
  || fail "late" "first timecode '$tc'"

# ---------------------------------------------------------------------- noise
ffmpeg -v error -y -f lavfi -i "color=c=0x141414:s=160x90:r=25:d=5" \
  -vf "geq=lum='$(walker_lum 1.0 0.82)':cb=128:cr=128,noise=alls=6" \
  -pix_fmt yuv420p -c:v libx264 "$OUT/noisy.mp4" 2>/dev/null
moon run cmd/moonfollow -- detect "$OUT/noisy.mp4" -o "$OUT/noisy.json" > /dev/null
got=$(steps_count "$OUT/noisy.json")
[ "$got" -ge 7 ] && [ "$got" -le 11 ] && ok "noisy walker: $got steps (9 +- 2)" \
  || fail "noisy" "got $got, want 9 +- 2"

# ----------------------------------------------------------------------- VFR
ffmpeg -v error -y -f lavfi -i "color=c=0x141414:s=160x90:r=25:d=2" "$OUT/seg-a.mp4" 2>/dev/null
ffmpeg -v error -y -f lavfi -i "color=c=0x141414:s=160x90:r=30:d=2" "$OUT/seg-b.mp4" 2>/dev/null
printf "file '%s/seg-a.mp4'\nfile '%s/seg-b.mp4'\n" "$OUT" "$OUT" > "$OUT/vfr-list.txt"
ffmpeg -v error -y -f concat -safe 0 -i "$OUT/vfr-list.txt" -c copy "$OUT/vfr.mp4" 2>/dev/null
if moon run cmd/moonfollow -- detect "$OUT/vfr.mp4" -o "$OUT/vfr.json" 2>&1 | grep -qi "variable frame rate"; then
  ok "VFR input: rejected cleanly"
else
  fail "vfr" "expected a variable-frame-rate rejection"
fi

echo "fixtures: $PASS cases passed in $OUT"
